### ISSUE TITLE
`Tcl`-related error when attempting to run under a virtual environment on Windows

### ISSUE THREAD

**Issue by ribbanya** [DRGN-DRC/Melee-Modding-Wizard#2]
Absolute paths converted to relative for privacy.
```
./Melee-Modding-Wizard/venv/Scripts/python.exe ./Melee-Modding-Wizard/main.py 
Traceback (most recent call last):
  File "./Melee-Modding-Wizard/main.py", line 2917, in <module>
    globalData.gui = gui = MainGui()
  File "./Melee-Modding-Wizard/main.py", line 1557, in __init__
    self.root = Tk.Tk()
  File "C:/Python27/lib/lib-tk/Tkinter.py", line 1825, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    C:/Python27/lib/tcl8.5 ./Melee-Modding-Wizard/venv/lib/tcl8.5 ./Melee-Modding-Wizard/lib/tcl8.5 ./Melee-Modding-Wizard/venv/library ./Melee-Modding-Wizard/library ./Melee-Modding-Wizard/tcl8.5.19/library ./tcl8.5.19/library



This probably means that Tcl wasn't installed properly.


Process finished with exit code 1
```

**Comment by DRGN-DRC** [comment]
This might become a non-issue once the project transitions to Python 3.
